# -*- coding: utf-8 -*-
"""Final_scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NfX305ofrHYNFbL8Qug5UTt_m7FIsfhW
"""

from bs4 import BeautifulSoup
import csv
import requests

import textwrap

source=requests.get('https://coreyms.com/').text
soup=BeautifulSoup(source,'lxml')

csv_file=open('scrapper.csv','w')
csv_writer=csv.writer(csv_file)
csv_writer.writerow(['Title','Summary','Youtube_Link'])      #passing a list of headers)

for article in soup.find_all("article"):
  headline=article.h2.a.text
  print(headline)
  print()

  summary=article.find('div',class_='entry-content')
  summary=summary.p.text
  my_wrap = textwrap.TextWrapper(width = 60)
  wrap_list = my_wrap.wrap(text=summary)
  for line in wrap_list:
   print(line)

  try:
    video_link=article.find('iframe', class_='youtube-player')
    src=str(video_link['src'])
    src=src.split('/')[-1]
    src=src.split("?")[0]
    link=f'https://www.youtube.com/watch?v={src}'
    
  except Exception as e:
    link=None
    
  print(link)

  csv_writer.writerow([headline,summary,link])